"""
Task domain entity.
Part of Domain layer - contains business logic and rules.
"""
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, List
from uuid import UUID


@dataclass
class Task:
    """
    Task domain entity.
    Represents a task that can be created, delegated, and tracked.
    """

    id: Optional[UUID]
    task_number: Optional[int]
    user_id: UUID
    title: str
    memo: Optional[str]
    delegated_to: Optional[UUID]
    due_date: Optional[str]  # Flexible: "2025-11-15", "next week", "december 2025"
    priority: str  # low, medium, high
    status: str  # new, in_progress, overdue, done, cancelled
    status_description: Optional[str]  # Free text with bullet points
    tags: List[str] = field(default_factory=list)
    completed_at: Optional[datetime] = None
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)

    # Valid values for enums
    VALID_PRIORITIES = ["low", "medium", "high"]
    VALID_STATUSES = ["new", "in_progress", "overdue", "done", "cancelled"]

    @classmethod
    def create(
        cls,
        user_id: UUID,
        title: str,
        memo: Optional[str] = None,
        delegated_to: Optional[UUID] = None,
        due_date: Optional[str] = None,
        priority: str = "medium",
        tags: Optional[List[str]] = None,
    ) -> "Task":
        """
        Factory method to create a new task.
        Enforces business rules at creation time.
        """
        # Validate title
        if not title or len(title.strip()) == 0:
            raise ValueError("Task title cannot be empty")

        if len(title) > 500:
            raise ValueError("Task title cannot exceed 500 characters")

        # Validate priority
        if priority not in cls.VALID_PRIORITIES:
            raise ValueError(
                f"Invalid priority: {priority}. Must be one of: {', '.join(cls.VALID_PRIORITIES)}"
            )

        # Validate due_date length if provided
        if due_date and len(due_date) > 200:
            raise ValueError("Due date cannot exceed 200 characters")

        now = datetime.utcnow()

        # Initial status description
        status_description = f"- [{now.strftime('%Y-%m-%d %H:%M')}] Taak aangemaakt"

        return cls(
            id=None,  # Will be set by repository
            task_number=None,  # Will be auto-generated by database
            user_id=user_id,
            title=title.strip(),
            memo=memo.strip() if memo else None,
            delegated_to=delegated_to,
            due_date=due_date.strip() if due_date else None,
            priority=priority,
            status="new",
            status_description=status_description,
            tags=tags or [],
            completed_at=None,
            created_at=now,
            updated_at=now,
        )

    def update_status(self, new_status: str, annotation: Optional[str] = None) -> None:
        """
        Update task status and add annotation to status description.

        Args:
            new_status: New status value
            annotation: Optional annotation to add to status description
        """
        if new_status not in self.VALID_STATUSES:
            raise ValueError(
                f"Invalid status: {new_status}. Must be one of: {', '.join(self.VALID_STATUSES)}"
            )

        old_status = self.status
        self.status = new_status
        self.updated_at = datetime.utcnow()

        # Add annotation to status description
        timestamp = self.updated_at.strftime("%Y-%m-%d %H:%M")
        new_line = f"- [{timestamp}] Status gewijzigd: {old_status} → {new_status}"

        if annotation:
            new_line += f" ({annotation})"

        if self.status_description:
            self.status_description += f"\n{new_line}"
        else:
            self.status_description = new_line

        # Set completed_at when task is marked as done
        if new_status == "done" and not self.completed_at:
            self.completed_at = self.updated_at
        elif new_status != "done":
            self.completed_at = None

    def add_annotation(self, annotation: str) -> None:
        """Add a timestamped annotation to status description."""
        if not annotation or len(annotation.strip()) == 0:
            raise ValueError("Annotation cannot be empty")

        timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M")
        new_line = f"- [{timestamp}] {annotation.strip()}"

        if self.status_description:
            self.status_description += f"\n{new_line}"
        else:
            self.status_description = new_line

        self.updated_at = datetime.utcnow()

    def delegate_to(self, person_id: UUID, person_name: str) -> None:
        """Delegate task to a person and add annotation."""
        self.delegated_to = person_id
        self.add_annotation(f"Gedelegeerd aan {person_name}")

    def update_priority(self, new_priority: str) -> None:
        """Update task priority with validation."""
        if new_priority not in self.VALID_PRIORITIES:
            raise ValueError(
                f"Invalid priority: {new_priority}. Must be one of: {', '.join(self.VALID_PRIORITIES)}"
            )

        old_priority = self.priority
        self.priority = new_priority
        self.add_annotation(f"Prioriteit gewijzigd: {old_priority} → {new_priority}")

    def update_due_date(self, new_due_date: Optional[str]) -> None:
        """Update due date and add annotation."""
        if new_due_date and len(new_due_date) > 200:
            raise ValueError("Due date cannot exceed 200 characters")

        old_due_date = self.due_date
        self.due_date = new_due_date.strip() if new_due_date else None

        if old_due_date and new_due_date:
            self.add_annotation(f"Deadline gewijzigd: {old_due_date} → {new_due_date}")
        elif new_due_date:
            self.add_annotation(f"Deadline toegevoegd: {new_due_date}")
        else:
            self.add_annotation("Deadline verwijderd")

    def add_tag(self, tag: str) -> None:
        """Add a tag if it doesn't exist."""
        tag = tag.strip().lower()
        if tag and tag not in self.tags:
            self.tags.append(tag)
            self.updated_at = datetime.utcnow()

    def remove_tag(self, tag: str) -> None:
        """Remove a tag if it exists."""
        tag = tag.strip().lower()
        if tag in self.tags:
            self.tags.remove(tag)
            self.updated_at = datetime.utcnow()

    def is_completed(self) -> bool:
        """Check if task is completed."""
        return self.status == "done"

    def is_overdue(self) -> bool:
        """Check if task is overdue."""
        return self.status == "overdue"

    def get_formatted_task_id(self) -> str:
        """Get formatted task ID (e.g., Task-00000001)."""
        if self.task_number is not None:
            return f"Task-{self.task_number:08d}"
        return "Task-????????"
